"""OKF envelope: bundle wrapping (M-v0.3.0-alpha placeholder).

M-v0.3.0+ 부터 구현:
- make_envelope(bundle_name, source, var_dir) -> Envelope: bundle 디렉터리 생성 + index.md 자동 생성
- parse_envelope(path) -> Envelope: bundle 디렉터리 read
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Envelope:
    """OKF bundle envelope (M-v0.3.0+ 구현)."""

    bundle_name: str
    source: str
    entries: list[Path]  # raw/ + concepts/ 파일 경로
    index_path: Path  # index.md 자동 생성
    created_at: str  # ISO 8601


def make_envelope(
    bundle_name: str, source: str, var_dir: Path
) -> Envelope:
    """bundle 디렉터리 생성 + index.md placeholder. M-v0.3.0+ 구현."""
    bundle_dir = var_dir / "concepts" / bundle_name
    bundle_dir.mkdir(parents=True, exist_ok=True)
    index_path = bundle_dir / "index.md"
    if not index_path.exists():
        index_path.write_text(
            f"# {bundle_name}\n\n"
            f"Source: `{source}`\n\n"
            f"_M-v0.3.0-alpha placeholder. Real index.md auto-generated by `make_envelope` in M-v0.3.0+._\n",
            encoding="utf-8",
        )
    return Envelope(
        bundle_name=bundle_name,
        source=source,
        entries=[],
        index_path=index_path,
        created_at="2026-06-23T00:00:00+09:00",
    )


def parse_envelope(path: Path) -> Envelope:
    """bundle 디렉터리 read. M-v0.3.0+ 구현."""
    raise NotImplementedError("M-v0.3.0-alpha placeholder")
